export const appContants = {
  METHOD_GET: "GET",
  METHOD_POST: "POST",
  METHOD_PATCH: "PATCH",

  // status
  PENDING: "_PENDING",
  FULFILLED: "_FULFILLED",
  REJECTED: "_REJECTED",

  //get users
  GET_USER: "GET_USER",
  POST_LOGIN_USER: "POST_LOGIN_USER",
  GET_USER_PENDING: "GET_USER_PENDING",
  GET_USER_FULFILLED: "GET_USER_FULFILLED",
  GET_USER_REJECTED: "GET_USER_REJECTED",
  //get species
  GET_SPECIES: "GET_SPECIES",
  GET_SPECIES_PENDING: "GET_SPECIES_PENDING",
  GET_SPECIES_FULFILLED: "GET_SPECIES_FULFILLED",
  GET_SPECIES_REJECTED: "GET_SPECIES_REJECTED",
  //get AGE
  GET_AGE: "GET_AGE",
  GET_AGE_PENDING: "GET_AGE_PENDING",
  GET_AGE_FULFILLED: "GET_AGE_FULFILLED",
  GET_AGE_REJECTED: "GET_AGE_REJECTED",
  //get PET
  GET_PET: "GET_PET",
  GET_PET_PENDING: "GET_PET_PENDING",
  GET_PET_FULFILLED: "GET_PET_FULFILLED",
  GET_PET_REJECTED: "GET_PET_REJECTED",
  //get PET BY ID User
  GET_PETBYUSER: "GET_PETBYUSER",
  GET_PETBYUSER_PENDING: "GET_PETBYUSER_PENDING",
  GET_PETBYUSER_FULFILLED: "GET_PETBYUSER_FULFILLED",
  GET_PETBYUSER_REJECTED: "GET_PETBYUSER_REJECTED",
  //get PET Detail
  GET_PET_DETAIL: "GET_PET_DETAIL",
  GET_PET_DETAIL_PENDING: "GET_PET_DETAIL_PENDING",
  GET_PET_DETAIL_FULFILLED: "GET_PET_DETAIL_FULFILLED",
  GET_PET_DETAIL_REJECTED: "GET_PET_DETAIL_REJECTED"
};
