export const appContants = {
  METHOD_GET: "GET",
  METHOD_POST: "POST",
  METHOD_PATCH: "PATCH",

  // status
  PENDING: "_PENDING",
  FULFILLED: "_FULFILLED",
  REJECTED: "_REJECTED",

  //post users
  POST_USER_LOGIN: "POST_USER_LOGIN",
  POST_USER_LOGIN_PENDING: "POST_USER_LOGIN_PENDING",
  POST_USER_LOGIN_FULFILLED: "POST_USER_LOGIN_FULFILLED",
  POST_USER_LOGIN_REJECTED: "POST_USER_REJECTED",
  //get users
  GET_USER: "GET_USER",
  GET_USER_PENDING: "GET_USER_PENDING",
  GET_USER_FULFILLED: "GET_USER_FULFILLED",
  GET_USER_REJECTED: "GET_USER_REJECTED",
  //get ticket
  GET_TICKET: "GET_TICKET",
  GET_TICKET_PENDING: "GET_TICKET_PENDING",
  GET_TICKET_FULFILLED: "GET_TICKET_FULFILLED",
  GET_TICKET_REJECTED: "GET_TICKET_REJECTED",
  //get ticket
  GETTIKET: "GETTIKET",
  GETTIKET_PENDING: "GETTIKET_PENDING",
  GETTIKET_FULFILLED: "GETTIKET_FULFILLED",
  GETTIKET_REJECTED: "GETTIKET_REJECTED",
  //store ticket
  POST_TICKET: "POST_TICKET",
  POST_TICKET_PENDING: "POST_TICKET_PENDING",
  POST_TICKET_FULFILLED: "POST_TICKET_FULFILLED",
  POST_TICKET_REJECTED: "POST_TICKET_REJECTED",
  //get trains
  GET_TRAINS: "GET_TRAINS",
  GET_TRAINS_PENDING: "GET_TRAINS_PENDING",
  GET_TRAINS_FULFILLED: "GET_TRAINS_FULFILLED",
  GET_TRAINS_REJECTED: "GET_TRAINS_REJECTED",
  //get order
  GET_ORDER: "GET_ORDER",
  GET_ORDER_PENDING: "GET_ORDER_PENDING",
  GET_ORDER_FULFILLED: "GET_ORDER_FULFILLED",
  GET_ORDER_REJECTED: "GET_ORDER_REJECTED",
  //get order byId
  GET_ORDER_BY: "GET_ORDER_BY",
  GET_ORDER_BY_PENDING: "GET_ORDER_BY_PENDING",
  GET_ORDER_BY_FULFILLED: "GET_ORDER_BY_FULFILLED",
  GET_ORDER_BY_REJECTED: "GET_ORDER_BY_REJECTED",
  //get order byId
  UPDATE_ORDER: "UPDATE_ORDER",
  UPDATE_ORDER_PENDING: "UPDATE_ORDER_PENDING",
  UPDATE_ORDER_FULFILLED: "UPDATE_ORDER_FULFILLED",
  UPDATE_ORDER_REJECTED: "UPDATE_ORDER_REJECTED"
};
